version: '3.5'

networks:

    app_network:
        name: "${PARSE_NETWORK:-parse}"

services:

    database:
        restart: always
        container_name: ${CN_DATABASE:-parse-mongo}
        image: bitnami/mongodb:latest
        environment:
            - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:?'Please, specify mongodb root password'}
            - MONGODB_USERNAME=${MONGODB_USERNAME:?'Please, specify mongodb database user'}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD:?'Please, specify db user password'}
            - MONGODB_DATABASE=${MONGODB_DATABASE:?'Please, specify application database'}
        ports:
            - "${PARSE_DB_PORT:-27017}:${PARSE_DB_PORT:-27017}"
        networks:
            - app_network
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/database:/bitnami"

    server:
        restart: always
        image: bitnami/parse:latest
#        build:
#            context: .
        depends_on:
            - database
        container_name: ${CN_SERVER:-parse}
        ports:
            - "${PARSE_PORT:-1337}:${PARSE_PORT:-1337}"
        environment:
            - PARSE_APP_FOLDER=${PARSE_APP_FOLDER:?'Please, specify parse app folder'}
            - PARSE_APP_ID=${PARSE_APP_ID:?'Please, specify parse app id'}
            - PARSE_MASTER_KEY=${PARSE_MASTER_KEY:?'Please, specify parse master key'}
            - MONGODB_HOST=${MONGODB_HOST:-parse-mongo}
            - PARSE_PORT_NUMBER=${PARSE_PORT:-1337}
            - PARSE_HOST=${PARSE_HOST:-localhost}
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/parse:/bitnami"
        networks:
            - app_network

    dashboard:
        restart: always
        container_name: ${CN_DASHBOARD:-parse-dashboard}
        image: bitnami/parse-dashboard:latest
#        depends_on:
#            - database
#            - server
        ports:
            - "${PARSE_DASHBOARD_PORT:-4040}:4040"
        networks:
            - app_network
        environment:
            - PARSE_DASHBOARD_APP_NAME
            - PARSE_DASHBOARD_USER
            - PARSE_DASHBOARD_PASSWORD
            - PARSE_HOST
            - PARSE_MASTER_KEY
            - PARSE_APP_ID
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/dashboard:/bitnami"


    proxy:
        restart: always
        image: handmadeapps/parseproxy
        build:
            context: .
            dockerfile: Dockerfile-httpd
        depends_on:
            - server
        container_name: ${CN_PROXY:-parse-proxy}
        ports:
            - "${PARSE_PROXY_PORT:-9090}:${PARSE_PROXY_PORT:-9090}"
        environment:
            - PROXY_SERVER_NAME=${PROXY_SERVER_NAME:-localhost}
            - PARSE_PROXY_PORT_NUMBER=${PARSE_PROXY_PORT:-9090}
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/httpd/logs:/logs"
        networks:
            - app_network


    proxy-dashboard:
        restart: always
        image: handmadeapps/parseproxydashboard
        build:
            context: .
            dockerfile: Dockerfile-httpd-dashboard
        depends_on:
            - dashboard
        container_name: ${CN_DASHBOARD_PROXY:-parse-proxy-dashboard}
        ports:
            - "${PARSE_PROXY_DASHBOARD_PORT:-8080}:${PARSE_PROXY_DASHBOARD_PORT:-8080}"
        environment:
            - PROXY_SERVER_NAME=${PROXY_SERVER_NAME:-localhost}
            - PARSE_DASHBOARD_PORT=${PARSE_PROXY_DASHBOARD_PORT:-8080}
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/httpd/logs:/logs"
        networks:
            - app_network


