version: '3.5'

networks:

    app_network:
        name: "${PARSE_NETWORK:-parse}"

services:

    database:
        restart: always
        container_name: parse-mongo
        image: bitnami/mongodb:latest
        environment:
            - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:?'Please, specify mongodb root password'}
            - MONGODB_USERNAME=${MONGODB_USERNAME:?'Please, specify mongodb database user'}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD:?'Please, specify db user password'}
            - MONGODB_DATABASE=${MONGODB_DATABASE:?'Please, specify application database'}
        ports:
            - "27017:27017"
        networks:
            - app_network
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/database:/bitnami"

    server:
        restart: always
        image: bitnami/parse:latest
#        build:
#            context: .
        depends_on:
            - database
        container_name: parse
        ports:
            - "${PARSE_PORT_NUMBER}:${PARSE_PORT_NUMBER}"
        environment:
            - PARSE_APP_FOLDER=${PARSE_APP_FOLDER:?'Please, specify parse app folder'}
            - PARSE_APP_ID=${PARSE_APP_ID:?'Please, specify parse app id'}
            - PARSE_MASTER_KEY=${PARSE_MASTER_KEY:?'Please, specify parse master key'}
            - MONGODB_HOST=${MONGODB_HOST:-parse-mongo}
            - PARSE_PORT_NUMBER=${PARSE_PORT_NUMBER:-1337}
            - PARSE_HOST=${PARSE_HOST:-localhost}
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/parse:/bitnami"
        networks:
            - app_network

    dashboard:
        restart: always
        container_name: parse-dashboard
        image: bitnami/parse-dashboard:latest
        depends_on:
            - database
            - server
        ports:
            - "4040:4040"
        networks:
            - app_network
        environment:
            - PARSE_DASHBOARD_APP_NAME
            - PARSE_DASHBOARD_USER
            - PARSE_DASHBOARD_PASSWORD
            - PARSE_HOST
            - PARSE_MASTER_KEY
            - PARSE_APP_ID
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/dashboard:/bitnami"


    proxy:
        restart: always
        image: handmadeapps/parseproxy
        build:
            context: .
            dockerfile: Dockerfile-httpd
        depends_on:
            - server
        container_name: parse-proxy
        ports:
            - "${PARSE_PROXY_PORT_NUMBER}:443"
        environment:
            - PROXY_SERVER_NAME=${PROXY_SERVER_NAME:-localhost}
            - PARSE_PROXY_PORT_NUMBER=${PARSE_PROXY_PORT_NUMBER:-9090}
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/httpd/logs:/logs"
        networks:
            - app_network


    proxy-dashboard:
        restart: always
        image: handmadeapps/parseproxydashboard
        build:
            context: .
            dockerfile: Dockerfile-httpd-dashboard
        depends_on:
            - dashboard
        container_name: parse-proxy-dashboard
        ports:
            - "${PARSE_DASHBOARD_PORT}:443"
        environment:
            - PROXY_SERVER_NAME=${PROXY_SERVER_NAME:-localhost}
            - PARSE_DASHBOARD_PORT=${PARSE_DASHBOARD_PORT:-8080}
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/httpd/logs:/logs"
        networks:
            - app_network


