version: '3.5'

networks:

    app_network:
        name: "${PARSE_NETWORK:-parse}"

services:

    database:
        restart: always
        container_name: parse-mongo
        image: mongo
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGO_INITDB_DATABASE
        networks:
            - app_network
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/database:/data/db"
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/config/database_init:/docker-entrypoint-initdb.d"

    parse:
        restart: always
        image: handmadeapps/parse-server
        build:
            context: .
        depends_on:
            - database
        container_name: parse-server
        ports:
            - "1337:1337"
        environment:
            - PARSE_SERVER_APPLICATION_ID=${PARSE_SERVER_APPLICATION_ID:?'Please, specify parse app id'}
            - PARSE_SERVER_MASTER_KEY=${PARSE_SERVER_MASTER_KEY:?'Please, specify parse master key'}
            - PARSE_SERVER_DATABASE_URI=${PARSE_SERVER_DATABASE_URI:?'Please, specify parse app db URI'}
            - PARSE_SERVER_URL
            - SENDGRID_API_KEY
            - SENDGRID_FROM_ADDRESS
        networks:
            - app_network

