version: '3.5'

networks:

    app_network:
        name: "${PARSE_NETWORK:-parse}"

services:

    database:
        restart: always
        container_name: parse-mongo
        image: bitnami/mongodb:latest
        ports:
            - "27017:27017"
        networks:
            - app_network
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/database:/bitnami"

    server:
        restart: always
        image: bitnami/parse:latest
#        build:
#            context: .
        depends_on:
            - database
        container_name: parse
        ports:
            - "${PARSE_PORT_NUMBER}:${PARSE_PORT_NUMBER}"
        environment:
            - PARSE_APP_FOLDER=${PARSE_APP_FOLDER:?'Please, specify parse app folder'}
            - PARSE_APP_ID=${PARSE_APP_ID:?'Please, specify parse app id'}
            - PARSE_MASTER_KEY=${PARSE_MASTER_KEY:?'Please, specify parse master key'}
            - MONGODB_HOST=${MONGODB_HOST:-parse-mongo}
            - PARSE_PORT_NUMBER=${PARSE_PORT_NUMBER:-1337}
            - PARSE_HOST=${PARSE_HOST:-localhost}
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/parse:/bitnami"
        networks:
            - app_network

    dashboard:
        restart: always
        container_name: parse-dashboard
        image: bitnami/parse-dashboard:latest
        depends_on:
            - database
            - server
        ports:
            - "${PARSE_DASHBOARD_PORT}:4040"
        networks:
            - app_network
        environment:
            - PARSE_DASHBOARD_PORT=${PARSE_DASHBOARD_PORT:-8080}
            - PARSE_DASHBOARD_APP_NAME
            - PARSE_DASHBOARD_USER
            - PARSE_DASHBOARD_PASSWORD
            - PARSE_HOST
            - PARSE_MASTER_KEY
            - PARSE_APP_ID
        volumes:
            - "${PARSE_APP_FOLDER:?'Please, specify app folder in .env file.'}/dashboard:/bitnami"


